services:
  mastobackup:
    image: ghcr.io/kevinisageek/mastobackup:main
    volumes:
      - mastobackup-data:/backups
      - mastobackup-state:/var/lib/tailscale
    env_file: .env
    restart: unless-stopped

volumes:
  mastobackup-state:
    driver_opts:
      type: "nfs"
      o: "addr=synology.kevinisageek.org,nfsvers=4"
      device: ":/volume1/docker/mastobackup" 
  mastobackup-data:
    driver_opts:
      type: "nfs"
      o: "addr=synology.kevinisageek.org,nfsvers=4"
      device: ":/volume1/backups"
